server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://main-db:5432/ewm_main
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

stats:
  service:
    url: http://stats-server:9090
    enabled: true

app:
  default-page-size: 10
  event:
    publication-min-hours: 1
  request:
    moderation-default: true

logging:
  level:
    ru.practicum: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG