services:
  main-db:
    image: postgres:16.1
    container_name: ewm-main-db
    environment:
      POSTGRES_DB: ewm_main
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - main-db-data:/var/lib/postgresql/data

  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-db
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    ports:
      - "5433:5432"
    volumes:
      - stats-db-data:/var/lib/postgresql/data

  stats-service:
    build:
      context: .
      dockerfile: stats/stats-server/Dockerfile
    container_name: stats-service
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: stats
      SERVER_PORT: 9090
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - stats-db

  main-service:
    build:
      context: .
      dockerfile: main-service/Dockerfile
    container_name: main-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://main-db:5432/ewm_main
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      STATS_SERVER_URL: http://stats-service:9090
      SERVER_PORT: 8080
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - main-db
      - stats-service

volumes:
  main-db-data:
  stats-db-data: