services:
  stats-server:
    build: stats-service/server
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats

  stats-db:
    image: postgres:16.1

  ewm-service:
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1
