services:
  stats-server:
    build: /stats/stats-server
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats

  stats-db:
    image: postgres:16.1

  ewm-service:
    build: ewm-service
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - stats-service.url=http://stats-server:9090

  ewm-db:
    image: postgres:16.1
